apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: fastapi
        image: gabs162/fastapi-weather:latest
        ports:
        - containerPort: 80
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openweather-secret
              key: api-key
