apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: fastapi
        image: gaabs16/fastapi-weather:1.0.123456
        ports:
        - containerPort: 80
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-secret
              key: WEATHER_API_KEY